-- ============================================================================
-- 04 - CONSTRAINT, PK, UNIQUE, CHECK E FOREIGN KEY
-- Versione corretta: prima PK/UNIQUE/CHECK, poi FOREIGN KEY.
-- Generato dall'inventario del progetto sorgente.
-- Eseguire SOLO sul nuovo progetto Supabase.
-- ============================================================================

ALTER TABLE public."abilitazioni_modifica" ADD CONSTRAINT "abilitazioni_modifica_pkey" PRIMARY KEY (user_id, ambito, anno_accademico);
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_pkey" PRIMARY KEY (user_id);
ALTER TABLE public."anagrafica_riservata" ADD CONSTRAINT "anagrafica_riservata_pkey" PRIMARY KEY (user_id);
ALTER TABLE public."anni_accademici" ADD CONSTRAINT "anni_accademici_pkey" PRIMARY KEY (codice);
ALTER TABLE public."eventi" ADD CONSTRAINT "eventi_pkey" PRIMARY KEY (id);
ALTER TABLE public."house_of_mentore" ADD CONSTRAINT "house_of_mentore_pkey" PRIMARY KEY (id);
ALTER TABLE public."house_of_mentore_opzioni" ADD CONSTRAINT "house_of_mentore_opzioni_pkey" PRIMARY KEY (id);
ALTER TABLE public."import_insegnamenti" ADD CONSTRAINT "import_insegnamenti_pkey" PRIMARY KEY (id);
ALTER TABLE public."import_partecipanti" ADD CONSTRAINT "import_partecipanti_pkey" PRIMARY KEY (id);
ALTER TABLE public."insegnamenti" ADD CONSTRAINT "insegnamenti_pkey" PRIMARY KEY (id);
ALTER TABLE public."mentoraggi" ADD CONSTRAINT "mentoraggi_pkey" PRIMARY KEY (id);
ALTER TABLE public."mentoraggio_mentori" ADD CONSTRAINT "mentoraggio_mentori_pkey" PRIMARY KEY (mentoraggio_id, mentore_id, tipo);
ALTER TABLE public."news" ADD CONSTRAINT "news_pkey" PRIMARY KEY (id);
ALTER TABLE public."notifiche_destinatari" ADD CONSTRAINT "notifiche_destinatari_pkey" PRIMARY KEY (id);
ALTER TABLE public."notifiche_dispositivi" ADD CONSTRAINT "notifiche_dispositivi_pkey" PRIMARY KEY (id);
ALTER TABLE public."notifiche_messaggi" ADD CONSTRAINT "notifiche_messaggi_pkey" PRIMARY KEY (id);
ALTER TABLE public."notifiche_regole" ADD CONSTRAINT "notifiche_regole_pkey" PRIMARY KEY (id);
ALTER TABLE public."partecipazioni_annuali" ADD CONSTRAINT "partecipazioni_annuali_pkey" PRIMARY KEY (user_id, anno_accademico);
ALTER TABLE public."partecipazioni_eventi" ADD CONSTRAINT "partecipazioni_eventi_pkey" PRIMARY KEY (evento_id, partecipante_id);
ALTER TABLE public."partecipazioni_house_of_mentore" ADD CONSTRAINT "partecipazioni_house_of_mentore_pkey" PRIMARY KEY (evento_id, partecipante_id);
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_pkey" PRIMARY KEY (id);
ALTER TABLE public."questionari_compilazioni" ADD CONSTRAINT "questionari_compilazioni_pkey" PRIMARY KEY (id);
ALTER TABLE public."questionari_domande" ADD CONSTRAINT "questionari_domande_pkey" PRIMARY KEY (id);
ALTER TABLE public."questionari_risposte" ADD CONSTRAINT "questionari_risposte_pkey" PRIMARY KEY (id);
ALTER TABLE public."questionari_template" ADD CONSTRAINT "questionari_template_pkey" PRIMARY KEY (id);
ALTER TABLE public."risorse_mentoring" ADD CONSTRAINT "risorse_mentoring_pkey" PRIMARY KEY (id);
ALTER TABLE public."ssd" ADD CONSTRAINT "ssd_pkey" PRIMARY KEY (cod_ssd);
ALTER TABLE public."user_roles" ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY (user_id);
ALTER TABLE public."house_of_mentore_opzioni" ADD CONSTRAINT "house_of_mentore_opzioni_id_evento_unique" UNIQUE (id, evento_id);
ALTER TABLE public."notifiche_destinatari" ADD CONSTRAINT "notifiche_destinatari_unique" UNIQUE (messaggio_id, user_id);
ALTER TABLE public."notifiche_dispositivi" ADD CONSTRAINT "notifiche_dispositivi_token_unique" UNIQUE (token);
ALTER TABLE public."notifiche_regole" ADD CONSTRAINT "notifiche_regole_codice_key" UNIQUE (codice);
ALTER TABLE public."questionari_compilazioni" ADD CONSTRAINT "questionari_compilazioni_questionario_id_user_id_key" UNIQUE (questionario_id, user_id);
ALTER TABLE public."questionari_domande" ADD CONSTRAINT "questionari_domande_template_id_ordine_key" UNIQUE (template_id, ordine);
ALTER TABLE public."questionari_risposte" ADD CONSTRAINT "questionari_risposte_compilazione_id_domanda_id_key" UNIQUE (compilazione_id, domanda_id);
ALTER TABLE public."risorse_mentoring" ADD CONSTRAINT "risorse_mentoring_storage_path_key" UNIQUE (storage_path);
ALTER TABLE public."abilitazioni_modifica" ADD CONSTRAINT "abilitazione_coerente" CHECK (abilitata = false OR abilitata_da IS NOT NULL AND abilitata_at IS NOT NULL);
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_email_valida" CHECK (email_unipa::text ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::text);
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_url_valido" CHECK (pagina_personale_unipa IS NULL OR pagina_personale_unipa::text ~* '^https?://'::text);
ALTER TABLE public."anni_accademici" ADD CONSTRAINT "anni_accademici_stato_check" CHECK (stato = ANY (ARRAY['preparazione'::text, 'attivo'::text, 'chiuso'::text]));
ALTER TABLE public."anni_accademici" ADD CONSTRAINT "date_anno_accademico_valide" CHECK (data_inizio IS NULL OR data_fine IS NULL OR data_fine >= data_inizio);
ALTER TABLE public."anni_accademici" ADD CONSTRAINT "formato_anno_accademico" CHECK (codice::text ~ '^[0-9]{4}-[0-9]{2}$'::text);
ALTER TABLE public."eventi" ADD CONSTRAINT "date_iscrizioni_evento_valide" CHECK (data_apertura_iscrizioni IS NULL OR data_chiusura_iscrizioni IS NULL OR data_chiusura_iscrizioni >= data_apertura_iscrizioni);
ALTER TABLE public."eventi" ADD CONSTRAINT "eventi_attivo_check" CHECK (attiva = ANY (ARRAY[true, false]));
ALTER TABLE public."eventi" ADD CONSTRAINT "eventi_locandina_url_check" CHECK (locandina_url IS NULL OR locandina_url ~* '^https?://'::text);
ALTER TABLE public."house_of_mentore" ADD CONSTRAINT "house_of_mentore_titolo_check" CHECK (length(TRIM(BOTH FROM titolo)) > 0);
ALTER TABLE public."house_of_mentore_opzioni" ADD CONSTRAINT "house_of_mentore_opzioni_descrizione_check" CHECK (length(TRIM(BOTH FROM descrizione)) > 0);
ALTER TABLE public."insegnamenti" ADD CONSTRAINT "cfu_positivo" CHECK (cfu > 0::numeric);
ALTER TABLE public."insegnamenti" ADD CONSTRAINT "ore_positive" CHECK (ore >= 0);
ALTER TABLE public."mentoraggi" ADD CONSTRAINT "link_questionario_valido" CHECK (link_questionario IS NULL OR link_questionario::text ~* '^https?://'::text);
ALTER TABLE public."partecipazioni_annuali" ADD CONSTRAINT "partecipazioni_annuali_stato_check" CHECK (stato = ANY (ARRAY['da_contattare'::text, 'confermato'::text, 'rinuncia'::text, 'nuovo'::text, 'sospeso'::text]));
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_riferimento_check" CHECK (provider = 'interno'::questionario_provider AND evento_id IS NOT NULL AND mentoraggio_id IS NULL OR provider = 'pubblico'::questionario_provider AND mentoraggio_id IS NOT NULL AND evento_id IS NULL);
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_url_esterno_check" CHECK (url_esterno IS NULL OR url_esterno ~* '^https?://'::text);
ALTER TABLE public."risorse_mentoring" ADD CONSTRAINT "risorse_mentoring_categoria_check" CHECK (categoria::text = ANY (ARRAY['Materiale di presentazione'::character varying, 'Materiale per l''attività di mentoraggio'::character varying, 'Materiale burocratico/amministrativo'::character varying, 'Altro'::character varying]::text[]));
ALTER TABLE public."abilitazioni_modifica" ADD CONSTRAINT "abilitazioni_modifica_abilitata_da_fkey" FOREIGN KEY (abilitata_da) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."abilitazioni_modifica" ADD CONSTRAINT "abilitazioni_modifica_anno_accademico_fkey" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."abilitazioni_modifica" ADD CONSTRAINT "abilitazioni_modifica_user_id_fkey" FOREIGN KEY (user_id) REFERENCES anagrafica(user_id) ON DELETE CASCADE;
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_anno_prima_partecipazione_fkey" FOREIGN KEY (anno_prima_partecipazione) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_cod_ssd_fkey" FOREIGN KEY (cod_ssd) REFERENCES ssd(cod_ssd) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."anagrafica" ADD CONSTRAINT "anagrafica_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."anagrafica_riservata" ADD CONSTRAINT "anagrafica_riservata_user_id_fkey" FOREIGN KEY (user_id) REFERENCES anagrafica(user_id) ON DELETE CASCADE;
ALTER TABLE public."eventi" ADD CONSTRAINT "eventi_anno_accademico_fkey" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."house_of_mentore" ADD CONSTRAINT "house_of_mentore_anno_accademico_fkey" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."house_of_mentore_opzioni" ADD CONSTRAINT "house_of_mentore_opzioni_evento_id_fkey" FOREIGN KEY (evento_id) REFERENCES house_of_mentore(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."insegnamenti" ADD CONSTRAINT "insegnamenti_docente_id_fkey" FOREIGN KEY (docente_id) REFERENCES anagrafica(user_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."mentoraggi" ADD CONSTRAINT "mentoraggi_anno_accademico_fk" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."mentoraggi" ADD CONSTRAINT "mentoraggi_insegnamento_id_fkey" FOREIGN KEY (insegnamento_id) REFERENCES insegnamenti(id) ON DELETE CASCADE;
ALTER TABLE public."mentoraggio_mentori" ADD CONSTRAINT "mentoraggio_mentori_mentoraggio_id_fkey" FOREIGN KEY (mentoraggio_id) REFERENCES mentoraggi(id) ON DELETE CASCADE;
ALTER TABLE public."mentoraggio_mentori" ADD CONSTRAINT "mentoraggio_mentori_mentore_id_fkey" FOREIGN KEY (mentore_id) REFERENCES anagrafica(user_id) ON DELETE RESTRICT;
ALTER TABLE public."notifiche_destinatari" ADD CONSTRAINT "notifiche_destinatari_messaggio_fk" FOREIGN KEY (messaggio_id) REFERENCES notifiche_messaggi(id) ON DELETE CASCADE;
ALTER TABLE public."notifiche_destinatari" ADD CONSTRAINT "notifiche_destinatari_user_fk" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."notifiche_dispositivi" ADD CONSTRAINT "notifiche_dispositivi_user_fk" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."notifiche_messaggi" ADD CONSTRAINT "notifiche_messaggi_anno_fk" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."notifiche_messaggi" ADD CONSTRAINT "notifiche_messaggi_creata_da_fk" FOREIGN KEY (creata_da) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."notifiche_messaggi" ADD CONSTRAINT "notifiche_messaggi_regola_fk" FOREIGN KEY (regola_id) REFERENCES notifiche_regole(id) ON DELETE SET NULL;
ALTER TABLE public."partecipazioni_annuali" ADD CONSTRAINT "partecipazioni_annuali_anno_accademico_fkey" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON DELETE RESTRICT;
ALTER TABLE public."partecipazioni_annuali" ADD CONSTRAINT "partecipazioni_annuali_confermato_da_fkey" FOREIGN KEY (confermato_da) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."partecipazioni_annuali" ADD CONSTRAINT "partecipazioni_annuali_user_id_fkey" FOREIGN KEY (user_id) REFERENCES anagrafica(user_id) ON DELETE CASCADE;
ALTER TABLE public."partecipazioni_eventi" ADD CONSTRAINT "partecipazioni_eventi_evento_id_fkey" FOREIGN KEY (evento_id) REFERENCES eventi(id) ON DELETE CASCADE;
ALTER TABLE public."partecipazioni_eventi" ADD CONSTRAINT "partecipazioni_eventi_partecipante_id_fkey" FOREIGN KEY (partecipante_id) REFERENCES anagrafica(user_id) ON DELETE RESTRICT;
ALTER TABLE public."partecipazioni_eventi" ADD CONSTRAINT "partecipazioni_eventi_presente_impostato_da_fkey" FOREIGN KEY (presente_impostato_da) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."partecipazioni_house_of_mentore" ADD CONSTRAINT "partecipazioni_house_of_mentore_evento_id_fkey" FOREIGN KEY (evento_id) REFERENCES house_of_mentore(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."partecipazioni_house_of_mentore" ADD CONSTRAINT "partecipazioni_house_of_mentore_partecipante_id_fkey" FOREIGN KEY (partecipante_id) REFERENCES anagrafica(user_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."partecipazioni_house_of_mentore" ADD CONSTRAINT "partecipazioni_house_opzione_evento_fk" FOREIGN KEY (opzione_id, evento_id) REFERENCES house_of_mentore_opzioni(id, evento_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_evento_id_fkey" FOREIGN KEY (evento_id) REFERENCES eventi(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_mentoraggio_id_fkey" FOREIGN KEY (mentoraggio_id) REFERENCES mentoraggi(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."questionari" ADD CONSTRAINT "questionari_template_id_fkey" FOREIGN KEY (template_id) REFERENCES questionari_template(id) ON DELETE RESTRICT;
ALTER TABLE public."questionari_compilazioni" ADD CONSTRAINT "questionari_compilazioni_questionario_id_fkey" FOREIGN KEY (questionario_id) REFERENCES questionari(id) ON DELETE CASCADE;
ALTER TABLE public."questionari_compilazioni" ADD CONSTRAINT "questionari_compilazioni_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."questionari_domande" ADD CONSTRAINT "questionari_domande_template_id_fkey" FOREIGN KEY (template_id) REFERENCES questionari_template(id) ON DELETE CASCADE;
ALTER TABLE public."questionari_risposte" ADD CONSTRAINT "questionari_risposte_compilazione_id_fkey" FOREIGN KEY (compilazione_id) REFERENCES questionari_compilazioni(id) ON DELETE CASCADE;
ALTER TABLE public."questionari_risposte" ADD CONSTRAINT "questionari_risposte_domanda_id_fkey" FOREIGN KEY (domanda_id) REFERENCES questionari_domande(id) ON DELETE CASCADE;
ALTER TABLE public."questionari_template" ADD CONSTRAINT "questionari_template_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."risorse_mentoring" ADD CONSTRAINT "risorse_mentoring_anno_accademico_fkey" FOREIGN KEY (anno_accademico) REFERENCES anni_accademici(codice) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."risorse_mentoring" ADD CONSTRAINT "risorse_mentoring_uploaded_by_fkey" FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
