// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcav1EUY47kUXyINnr82Ux0Smu5Z4v42g',
    appId: '1:168070790692:web:b24306731b3e54efb4e2b1',
    messagingSenderId: '168070790692',
    projectId: 'progmentore-9b804',
    authDomain: 'progmentore-9b804.firebaseapp.com',
    storageBucket: 'progmentore-9b804.firebasestorage.app',
    measurementId: 'G-VCY5Y962KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhOxTXvcMlAhEz9iOSvHTdqysLT0rsDg',
    appId: '1:168070790692:android:dfd67721b1bf5dc5b4e2b1',
    messagingSenderId: '168070790692',
    projectId: 'progmentore-9b804',
    storageBucket: 'progmentore-9b804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgwuos0a7Z61SZOav1ZFPq23KP_znSTQ',
    appId: '1:168070790692:ios:29bbb6ea38236034b4e2b1',
    messagingSenderId: '168070790692',
    projectId: 'progmentore-9b804',
    storageBucket: 'progmentore-9b804.firebasestorage.app',
    iosBundleId: 'com.example.progMentore',
  );
}
